### ISSUE TITLE
String interpolation of most keywords leads to double free error

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho-libmorpho#16]
Running the following code
`print “The keyword is ${while}”`

results in a double free error:
```
morpho6(62148,0x1db5ed000) malloc: Double free of object 0x122e1f200
morpho6(62148,0x1db5ed000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      morpho6 test.morpho
```

whereas the expected output should be some error highlighting that the input is a keyword. 

Certain keywords that have values, like `nil`, `true`, work fine in the above. 

With `self`, I am getting a reasonable error:
```
Error 'SlfOtsdClss' [line 1 char 24] : Cannot use 'self' outside of a class.
```
but `super` leads to double free.

**Comment by softmattertheory** [comment]
Thanks for this @joshichaitanya3; I am noticing a number of issues with string interpolation that I'm going to look into. I'll send updates when I have more information.

**Comment by softmattertheory** [comment]
It seems that this issue has been solved with today's PR. Thanks for reporting this @joshichaitanya3!
